name: cmems
channels:
  - conda-forge
dependencies:
  - matplotlib
  - numpy
  - pandas
  - xarray 
  - netcdf4
  - h5netcdf
  - cartopy
  - scipy
  - pip
  - pip:
    - copernicusmarine>=1.0<=2.0
  - python>=3.9,<3.12